### ISSUE TITLE
STEP format ?

### ISSUE THREAD

**Issue by marcething** [Lodran/Akimbo#1]
Hi,
Can you please send the source files in STEP format or convert them to STEP please?
Thanks in advance for your reply
Best regards

Marc

**Comment by Lodran** [comment]
Sorry, Akimbo was designed as a parametric model in OpenSCAD, which doesn't have the ability to export STEP.

That said, apparently you can use an Addon module for FreeCAD to do the conversion.

https://forum.lulzbot.com/viewtopic.php?f=8&t=243
